navbar:
  blog_title: yxibng


about:
  name: "yxibng"
  intro: "iOS、C、C++"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/yxibng', tip: 'GitHub' }
index:
  slogan:
    enable: true
    text: 读书，学习，走遍世界
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]